# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Solebutton = QtWidgets.QPushButton(self.centralwidget)
        self.Solebutton.setGeometry(QtCore.QRect(390, 360, 201, 81))
        self.Solebutton.setObjectName("Solebutton")
        self.Wiibutton = QtWidgets.QPushButton(self.centralwidget)
        self.Wiibutton.setGeometry(QtCore.QRect(390, 480, 201, 81))
        self.Wiibutton.setObjectName("Wiibutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 160, 561, 181))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(-4, -4, 121, 91))
        self.logo.setStyleSheet("background-image: url(:/pictures/Pictures/ezgif.com-gif-maker);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/pictures/Pictures/ezgif.com-gif-maker"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Solebutton.setText(_translate("MainWindow", "Soles Programm"))
        self.Wiibutton.setText(_translate("MainWindow", "Wii Board Programm"))
        self.label.setText(_translate("MainWindow", "Choose the Programm you want to run"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
