# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wiiwindow(object):
    def setupUi(self, wiiwindow):
        wiiwindow.setObjectName("wiiwindow")
        wiiwindow.resize(1920, 1080)
        self.graphicsView = QtWidgets.QGraphicsView(wiiwindow)
        self.graphicsView.setGeometry(QtCore.QRect(190, 10, 951, 641))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(wiiwindow)
        self.label.setGeometry(QtCore.QRect(0, 0, 181, 111))
        self.label.setStyleSheet("background-image: url(:/pictures/Pictures/ezgif.com-gif-maker);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pictures/Pictures/ezgif.com-gif-maker"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(wiiwindow)
        self.label_2.setGeometry(QtCore.QRect(1160, 70, 661, 501))
        self.label_2.setStyleSheet("background-image: url(:/pictures/Pictures/wiifront.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/pictures/Pictures/wiifront.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(wiiwindow)
        self.label_3.setGeometry(QtCore.QRect(380, 660, 551, 321))
        self.label_3.setStyleSheet("background-image: url(:/pictures/Pictures/wiiback.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/pictures/Pictures/wiiback.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(wiiwindow)
        QtCore.QMetaObject.connectSlotsByName(wiiwindow)

    def retranslateUi(self, wiiwindow):
        _translate = QtCore.QCoreApplication.translate
        wiiwindow.setWindowTitle(_translate("wiiwindow", "Form"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wiiwindow = QtWidgets.QWidget()
    ui = Ui_wiiwindow()
    ui.setupUi(wiiwindow)
    wiiwindow.show()
    sys.exit(app.exec_())
